# Generated by Django 4.1.7 on 2023-06-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTC_crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptobtc',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
